project: multiclass
run_name: ""

stages:
  train: true
  test: true
  origin_test: false

dataset:
  root: data
  patch: ndb_ufes/patch_level/images
  origin: ndb_ufes/origin_level/images
  fold_assignments_path: data/ndb_ufes/patch_level/csvs/fold_assignments_patch_level_with_images.csv
  cv_folds: [0, 1, 2, 3, 4]
  test_fold: 5

training:
  mode: finetune # expected options [finetune, frozen_head]

early_stopping:
  enabled: true
  patience: 10
  min_delta: 0.001
  mode: all

experiment:
  models:
    - resnet50
    - mobilenetv2
    - densenet121
    - vgg16
    - efficientnetb4
    - uni
    - virchow
    - ctranspath
    - mocov3_vit_small
    - vit_base_patch16_224
    - vit_large_patch16_224
    - vit_base_patch32_224
    - deit_base_patch16_224
    - swin_base_patch4_window7_224
    - efficientnet_b0
    - efficientnet_b1

hyperparameters:
  optimizer:
    name: sgd
    learning_rate: 0.01
    momentum: 0.9
  scheduler:
    name: reduce_lr_on_plateau
    other:
      # factor: 0.1
      # patience: 5
      mode: min
      factor: 0.1
      patience: 5
      min_lr: 0.000001
  model:
    name: resnet50
    other:
  other:
    loss: cross_entropy
    loss_weights: true
    folds: 5
    epochs: 200
    batch_size: 30
    train_type: cross_validation

device: mps
node_type: float32

# test:
#   model_path:
